### ISSUE TITLE
Time to run protocols with nested compound vertices increases with number of samplings

### ISSUE THREAD

**Issue by raynol-dsouza** [pyiron/pyiron_contrib#86] opened 2021-02-24 20:46 UTC
While updating `ProtocolFTSEvolutionParallel`, I came across a strange bug. The mentioned protocol runs in the following manner:

1. Initialize stuff: Run an bunch of `Primitive` vertices once for the entire run.
2. Run the nested `Compound` vertex, (compound, as it is made up of many primitive vertices) up to a sampling period:  Run parallel for each image. This compound vertex is a `_ConstrainedMD` protocol.
3. Update the string: Take the output of the compound vertex, do post processing.
4. Check if converged: Either to a convergence criterion or a hard limit on the number of steps.
5. Repeat step 2. by taking updated values from step 3., until convergence is reached.

The first thing that I noticed was this line that I print for a sanity check: 

`Sample no. 1 collected in 90.06782865524292 seconds` 

This is step 2 run for the 1st time.

After several loops, I have the following line printed:

```
Sample no. 50 collected in 183.9019513130188 seconds
...
Sample no. 75 collected in 212.11999106407166 seconds
...
Sample no. 150 collected in 281.00758814811707 seconds
```

This is step 2 run for the 150th time.

Ideally, the time required to run each sample should be the same, in this case, around 90 seconds. However, the time taken increases with the number of samples.

Further, I also took a look at the `ProtocolHarmonicTILDParallel`, and increased the frequency of convergence checks (for which, similar to FTS, it comes out of the nested `CompoundVertex`, checks for convergence, and runs the nested `CompondVertex` again if unconverged). This also shows the same increase in runtime.

I believe this issue may be arising due to memory allocation. I observed that the memory consumption also scaled similarly with increasing sampling. It looks like coming out of the nested `CompoundVertex`, updating something, and then returning to the nested `CompoundVertex `does not replace the older data, but appends to it somehow. But I haven't found any extra data in the input/output dictionaries of the `CompoundVertex`, which has got me perplexed.

The `reference_ job` also seems to grow in size with increasing sampling. This may be directly related.

**Comment by liamhuber** [comment] 2021-02-25 08:51
I'm not so shocked we run into hiccups here, the interactive jobs are not the cleanest and our interaction with them via `ExternalHamiltonian` is a bit hacky.

I just went back and took a look at `ExternalHamiltonian._initialize` and see that we set this:

```python
            if isinstance(job, LammpsInteractive) and fast_lammps_mode:
                # Note: This might be done by default at some point in LammpsInteractive,
                # and could then be removed here
                job.interactive_flush_frequency = 10 ** 10
                job.interactive_write_frequency = 10 ** 10
```

I still don't really understand the interactive jobs super well, but I think this means that we're effectively never clearing the cached data in ram, but also never writing it to disc (ok, never = until the job stops). This would be consistent with your observation that memory consumption increases but nothing untoward shows up in the vertex input/output -- all the extra data is hiding in the caches of the child jobs. 

I don't know enough about the interactive jobs atm to suggest a fix, but I hope that points in the right direction. I would also suggest making plots of time vs step (which I guess you already have the data for) and RAM vs step (this might be hard, maybe there's a shell or python script for this?). If my suspicion above is correct RAM vs step is just linear, and runtime vs step is sub-linear because some loading process takes linearly more time but the calculations themselves are constant in time.

**Comment by raynol-dsouza** [comment] 2021-02-25 18:07
>  I would also suggest making plots of time vs step (which I guess you already have the data for) and RAM vs step (this might be hard, maybe there's a shell or python script for this?). If my suspicion above is correct RAM vs step is just linear, and runtime vs step is sub-linear because some loading process takes linearly more time but the calculations themselves are constant in time.

@liamhuber It is exactly as you predicted -- RAM vs step is linear, and runtime vs step is still linear, but a bit more noisy. 

I tried `Cvertex.finish()` after running `Cvertex.execute_parallel()`, hoping that the `Cvertex` dumps before re-running the next iteration, but it didn't help. I also tried clearing the input/output dictionaries after for the `Cvertex` after the iteration, that didn't help either. Re-creating new reference jobs for every iteration also had no success.

The RAM usage spikes ONLY when the `Cvertex` is running, and drops when it isn't running (essentially,  like a square wave). 

I can still run the Protocol, but it just takes too long if I need to sample more (which for FTS, is super essential), and may also hit the RAM limit if I run for say, over 500 samples of 10k steps each.

**Comment by liamhuber** [comment] 2021-02-25 21:42
> I tried Cvertex.finish() after running Cvertex.execute_parallel(), hoping that the Cvertex dumps before re-running the next iteration, but it didn't help. I also tried clearing the input/output dictionaries after for the Cvertex after the iteration, that didn't help either. Re-creating new reference jobs for every iteration also had no success.

Honestly, I still suspect this is the right place to keep pushing. From the rest of your description it really sounds like there is some buffered array in the child job(s) that is getting out of control. Do you actually delete the child job(s) before recreating, or just recreate? I wonder if somehow even shutting `finishing` the vertex and closing the interactive jobs is not doing enough to release their memory footprint? 

I'm sorry I don't have more specific advice here, but I remain highly suspicious of `ExternalHamiltonian`, and any further profiling of the costs you can do to confirm or deny those suspicions would be helpful for getting my thinking to the next step.

**Comment by raynol-dsouza** [comment] 2021-02-26 00:19
> Do you actually delete the child job(s) before recreating, or just recreate?

Yep. I run `_initialize` again, and set `job.run(delete_existing_job=True)`.

>  I wonder if somehow even shutting finishing the vertex and closing the interactive jobs is not doing enough to release their memory footprint?

This really seems to be the case. What bothers me more, is that the size of the `reference_job.h5` keeps growing, while no visible extra data is added to the file.

I am currently also looking at possible ways I can clear the cache of the RAM that my job uses on the node, without affecting other jobs running on the same node.

**Comment by liamhuber** [comment] 2021-02-26 07:52
> What bothers me more, is that the size of the reference_job.h5 keeps growing, while no visible extra data is added to the file.

Yes, that's confusing and disconcerting to me too. I thought we made straight up copies of the reference jobs, so why is it increasing in size at all?

> I am currently also looking at possible ways I can clear the cache of the RAM that my job uses on the node, without affecting other jobs running on the same node.

I think we should try to solve the cause rather than treat the symptom, but it certainly doesn't hurt for you to learn a bit about this topic. I don't know how to handle the external codes, but for the protocols themselves you would want to look into [forcing the garbage collection](https://docs.python.org/3/library/gc.html). This is something you need to think about all the time in C/C++ (usually in the context of "memory leaks") and thankfully python does a very good job of automating the task, but it does have tools for doing things manually.

**Comment by raynol-dsouza** [comment] 2021-02-26 16:35
> I don't know how to handle the external codes, but for the protocols themselves you would want to look into forcing the garbage collection. This is something you need to think about all the time in C/C++ (usually in the context of "memory leaks") and thankfully python does a very good job of automating the task, but it does have tools for doing things manually.

I tried using `gc.collect()`, but that didn't fix the issue.

I will leave it as is for now, and comeback to the issue when I have an epiphany. :P

**Comment by liamhuber** [comment] 2021-03-08 07:59
@raynol-dsouza , did you manage to track down a `close` method for the parallelization and test it?

**Comment by raynol-dsouza** [comment] 2021-03-08 08:30
@huber no, not yet. Still looking into it.

**Closed** 2021-03-18 11:36 UTC
Labels: bug, question
