### ISSUE TITLE
Should every node run to get the output in workflow?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_contrib#688] opened 2023-05-23 10:16 UTC
Let's take this example:

```python
@node("y")
def add_one(x: int) -> int:
    return x + 1

@node("y")
def add_two(x: int) -> int:
    return x + 2
```

The workflow of these two works like this:

```python
n_1 = add_one(x=3)
n_1.run()
n_2 = add_two(x=n_1.outputs.y)
n_2.run()
```

but I would have expected the following code should be also valid (and it isn't):

```python
n_1 = add_one(x=3)
n_2 = add_two(x=n_1.outputs.y)
n_2.run()
```

Is this supposed to be like this?

**Comment by liamhuber** [comment] 2023-05-23 17:19
> ok then I think it needs a better error message for the case I mentioned above, because it raises `TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'` and it doesn't really tell me what I should have done.

IMO the current error message is quite already informative: you tried to run the function `return x + 2` and got informed that `x` is `None`. Don't read too much magic into `n_2.run()` -- all it's doing is trying to execute the decorated function.

I am certainly open to augmenting the error message to give more context, eg `f"the following error was raised by the node {node.label} with the inputs {*some_inputs_list}"`. Last week I already tried something like this naively with `raise ... as e` and modifying `e.message` or something, but didn't work immediately as I had hoped and I didn't bother fighting with it at the time.

**Comment by samwaseda** [comment] 2023-05-26 09:09
In this specific example it is good enough, but take a look at the following code (I hope the example is simple enough without comments, but otherwise there's no need to understand it in detail):

```python
from pyiron_contrib.workflow.workflow import Workflow
import wikipedia

def get_search(keyword: str, index: int=0) -> str:
    return wikipedia.search(keyword)[index]

def get_summary(keyword: str) -> str:
    return wikipedia.summary(keyword)

wf = Workflow('workflow')

wf.add.Node(get_search, 'search_result')
wf.add.Node(get_summary, 'summary')

wf.get_summary.inputs.keyword = wf.get_search.outputs.search_result

wf.get_search.inputs.keyword = 'iron'
wf.get_search.inputs.index = 0

# wf.get_search() # This line is needed to make it error-free
wf.get_summary()
```

The error here is

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 20
     17 wf.get_search.inputs.keyword = 'iron'
     18 wf.get_search.inputs.index = 0
---> 20 wf.get_summary()

File ~/dev/pyiron_contrib/pyiron_contrib/workflow/node.py:494, in Node.__call__(self)
    493 def __call__(self) -> None:
--> 494     self.run()

File ~/dev/pyiron_contrib/pyiron_contrib/workflow/node.py:478, in Node.run(self)
    476     self.running = False
    477     self.failed = True
--> 478     raise e
    480 if len(self.outputs) == 1:
    481     function_output = (function_output,)

File ~/dev/pyiron_contrib/pyiron_contrib/workflow/node.py:474, in Node.run(self)
    471 self.failed = False
    473 try:
--> 474     function_output = self.node_function(**self.inputs.to_value_dict())
    475 except Exception as e:
    476     self.running = False

Cell In[10], line 8, in get_summary(keyword)
      7 def get_summary(keyword: str) -> str:
----> 8     return wikipedia.summary(keyword)

File ~/conda/lib/python3.11/site-packages/wikipedia/util.py:28, in cache.__call__(self, *args, **kwargs)
     26   ret = self._cache[key]
     27 else:
---> 28   ret = self._cache[key] = self.fn(*args, **kwargs)
     30 return ret

File ~/conda/lib/python3.11/site-packages/wikipedia/wikipedia.py:231, in summary(title, sentences, chars, auto_suggest, redirect)
    216 '''
    217 Plain text summary of the page.
    218 
   (...)
    226 * redirect - allow redirection without raising RedirectError
    227 '''
    229 # use auto_suggest and redirect to get the correct article
    230 # also, use page's error checking to raise DisambiguationError if necessary
--> 231 page_info = page(title, auto_suggest=auto_suggest, redirect=redirect)
    232 title = page_info.title
    233 pageid = page_info.pageid

File ~/conda/lib/python3.11/site-packages/wikipedia/wikipedia.py:280, in page(title, pageid, auto_suggest, redirect, preload)
    278   return WikipediaPage(pageid=pageid, preload=preload)
    279 else:
--> 280   raise ValueError("Either a title or a pageid must be specified")

ValueError: Either a title or a pageid must be specified
```

I don't think it's immediately clear what I did wrong from this error message.

The point here is that I think an error message should point to the very origin of the problem, and not the symptom. Especially in this case we know that the node before is not ready, so it's relatively easy to detect it and raise an error.

This being said, I'm not saying **you** must do it. I just want to be on the same page to be sure that I don't start submitting changes that totally go against your ideas. And based on your last comment I assume you are okay with raising an error here, so I'm gonna open a PR myself.

**Comment by liamhuber** [comment] 2023-05-26 15:17
Sorry, I saw your issue comment and had a reply but I was doing breakfast with my kids and didn't get to it in time! #693 is a great idea, but it's just `Node.update`. 

I think it's a great idea, but I don't think we should double implement it. In fact, I think it's important that we have a public method that _forces_ the node function to evaluate. I'm certainly open to discussing naming, like maybe we should switch `update`->`run` and `run`->`force_run`, but I do want to keep both concepts available. It's probably also worth adding an `update` channel to the signals input too.

Regarding your example, I can still get behind providing extra context _around_ that error, but I don't want to do something that overwrites that error. IMO users need to be able to cleanly see errors raised by the code they're trying to run. Maybe the input _is_ what they think it is and yet still raises an error! By the time `node_function` raises the error, we're past the point of not showing it to the user. I also don't really want to do post-facto tree traversals to go back and check whether the inputs are `connected` to things that have(n't) run, although I don't 100% veto it...

> This being said, I'm not saying you must do it. I just want to be on the same page to be sure that I don't start submitting changes that totally go against your ideas. And based on your last comment I assume you are okay with raising an error here, so I'm gonna open a PR myself.

I am super happy if you open PRs! I also appreciate all the attention you've been giving `.workflows`. I think we're on the same page here for intention, in this particular case it's just a matter of me being more familiar with the (current!) architecture and the fact we do input readiness checks somewhere _other_ than `run`.

I'm going to go leave a terse and rude-sounding reply on the PR now, with the context that my full and more appreciative sentiments are expressed verbosely here 😆

**Comment by liamhuber** [comment] 2023-05-26 17:35
> In other words, the fact that `None` is entered for the argument is due to the current implementation of `Workflow`, because None was not chosen by the user anywhere. In this regard, we are not really overwriting an error, because they would have seen a `TypeError` in this case if they hadn't used `Workflow`.

Hmm, I see your point, although the fact is that the user _has_ chosen to pass `None` by the very virtue of using a workflow! Transforming the function into a node creates defined IO for it. We can certainly check if all the input is there (the `ready` check we're decided where to best use), but other than that I only see two options:
- Define some other data type like `NotData` and initialize output channels with that instead of `None`. I don't hate this, but I don't really like it either.
- _After_ something goes wrong, go back and look up the tree to see if you have connected input channels that connect to something that isn't run. This is tricky, because maybe the upstream node output `None` on purpose. Also there can be multiple input connections. Overall I _really_ don't like it.


So under the condition that the user says "ok, evaluate this node _now_", I'm actually OK with the current error system.

That still leaves the question, what should be "ok, evaluate this node _now_"?

> Both `run` and `__call__` can run even if `self.ready` is `False`

> I would suggest to move `if self.ready` to `run`. What do you think?

Since `__call__` is just wrapping `run`, I really don't like this. We need to offer _some_ public method for the user to force a node to evaluate given the input it has, and for me `run` is a perfectly reasonable name for this behaviour.

However, I see your point that some middle ground is necessary. `Update` is _too_ passive because of the extra flag. You nicely point out that `__call__` holds no specialization, so I'd be content to do the readiness check there.

I do want to stop to think about what the use case is. If we are forcing a node to `run` do we really want it to do something other than raise an error if it not `ready`? In the context of a workflow, I think we want some error so it can stop the workflow. In the context of playing in a notebook with individual nodes, seeing the error is also ok because you can just fix things and re-execute your run command -- although here I see the merit for augmenting the error message with a comment about the readiness of each input channel, in case that was the issue, but we do still want an error.

So for automated behaviour in workflows I still think it is doing what should be done. For interactive behaviour in notebooks we should have (a) a better error message, and (b) an intermediate seriousness between `update` and `run`.

For (b) perhaps this could be 

```python
def __call__(self):
    if self.ready:
        self.run()
```

(i.e. #693 but moved over to `__call__`)

Or maybe it would be useful to have something like this?

```python
def get_output(self):
    if self.ready():
        self.run()
        return self.output.to_dict()
    else:
        return None
```

**Comment by samwaseda** [comment] 2023-05-26 18:02
> * Define some other data type like `NotData` and initialize output channels with that instead of `None`. I don't hate this, but I don't really like it either.

I think something like this will anyway be needed at some point, because in parallel to this topic I was thinking about something like this:

```python
from pyiron_contrib.workflow.workflow import suspend


def get_energy(structure):
    vasp = pr.create.job.Vasp("vasp")
    if vasp.status.finished:
        return vasp.output.energy_pot[-1]
    vasp.structure = structure
    vasp.server.queue = "cm"
    vasp.run()
    return suspend
```

And this `suspend` will change the status inside `Workflow` to `running`, and it also stops subsequent nodes. This could be equivalent to your `NotData`. So maybe we can come up with a more generic name to suspend the workflow?

**Comment by liamhuber** [comment] 2023-05-26 18:13
If the node is executing its task on the same python process as the workflow, it will suspend itself anyway. If runs somewhere else (ie the node has a non-Nine executor), I had been thinking to capture this in the run command and simply let the run function finish without updating the nodes output -- that update would be triggered by a callback the node gives to the executor. One advantage here is that the workflow is not truly suspended, but if there are other nodes in the update stack the workflow will keep working on them. Eventually it will run out of stuff to do, and then will be de facto suspended until one of the nodes with an executor gets its callback triggered, updates its output, and pushes that data through the graph triggering more node updates.

All that said, I haven't actually implemented anything with executors, and this sort of custom return signal is a perfectly viable alternative. I think we'll need to get some executors working and really play around with it to see which set of (dis)advantages is best for us.

**Comment by samwaseda** [comment] 2023-05-27 20:05
> If the node is executing its task on the same python process as the workflow, it will suspend itself anyway.

Yeah that's not the situation I wanted to talk about here, but yes, for this point we agree

> If runs somewhere else (ie the node has a non-Nine executor), I had been thinking to capture this in the run command and simply let the run function finish without updating the nodes output -- that update would be triggered by a callback the node gives to the executor.

But that's more closely related to `TinyBase`, isn't it? In particular, the main advantage of the current workflow class is that it can make a node out of a simple python function straightforwardly, so there's in principle no separation. So I think we need to provide something that suspends the workflow from the function.

**Comment by liamhuber** [comment] 2023-05-29 17:24
> But that's more closely related to `TinyBase`, isn't it? In particular, the main advantage of the current workflow class is that it can make a node out of a simple python function straightforwardly, so there's in principle no separation. So I think we need to provide something that suspends the workflow from the function.

I don't know how much extra-credit reading you've done/want to do 😉 but Joerg and I have had some longer discussions [here](https://github.com/pyiron/ironflow/issues/175) and [here](https://github.com/pyiron/ironflow/issues/194). Most relevant right now is [this nice sketch](https://github.com/pyiron/ironflow/issues/175#issuecomment-1497886696) he made conceptualizing nodes as task-generators. In this way we could have `Node.executor` which defaults to `None` to run on the parent python process, but can be set to something more sophisticated to handle background or queue execution. So we really want to pull some of these ideas from `tiny_base` right in.

Again, I'm not trying to suggest that that's _the_ solution, just that it is a plausible (and for me, atm, most-desired) path forward for handling the root cause of why we need "suspension" capabilities. To be very specific, I can imagine breaking in [here](https://github.com/pyiron/pyiron_contrib/blob/ed60e2eb6debecd5673f0bc0729611fd8c7936e0/pyiron_contrib/workflow/node.py#L482) to pass the function and arguments off to an executor whenever `self.executor is not None`. Then I would pull out everything [from here onwards](https://github.com/pyiron/pyiron_contrib/blob/ed60e2eb6debecd5673f0bc0729611fd8c7936e0/pyiron_contrib/workflow/node.py#LL488C1-L488C1) into a separate function and pass that as a callback to the executor (again, when it's not `None`) and just return. This would free up the main interpreter process and just leave the node dangling in a `running` state (probably we want to be more informative, like `running-EXECUTOR_ID` or something, but w/e). Then whenever the callback gets triggered we handle the construction (probably deserialization) of `function_output`, the `out.update` business, and setting the new node state.

**Comment by samwaseda** [comment] 2023-05-30 14:27
ok it took me some time to understand all the stuff (and I'm sure I missed quite some important items). I still think we are on the same page. The question is what is exactly the value that is returned in [the very line you cited](https://github.com/pyiron/pyiron_contrib/blob/ed60e2eb6debecd5673f0bc0729611fd8c7936e0/pyiron_contrib/workflow/node.py#L482) if the user is wrapping an existing function, like `get_energy` in my example. I wanted to suggest to create a variable `suspend`, which could be something like:

```python
from typing import TypeVar
suspend = TypeVar("suspend")
```

And whenever there's an output we can check if the variable is `suspend` (I'm sure there's a more elegant way to do it). In principle the same one can be used for the input, to indicate that the execution should not be performed.

If I'm telling me nonsense forgive me XD

**Comment by liamhuber** [comment] 2023-05-30 17:04
I think it might be nonsense, sorry 😝 

Where would such a return value be used? Having a return value at all suggests that there's some sort of `foo  = node.run()`, but that's just not the case with the current architecture. The workflow isn't a master object controlling the flow, the flow is entirely determined by the connections -- with `update`s getting triggered as data gets pushed along data connections, and `run` getting triggered if there are `signal` connections.

I think your `get_energy` example is feeling weird because it's mixing old and new pyiron by explicitly running a non-modal job inside the function; the function isn't actually intended to return something on a single call, but requires a _minimum_ of two calls. It's also got  a global `pr:Project` floating around. Basically, the old job classes are a pain to wrap in an idempotent and functional world. In the new paradigm, the closest thing to this you can easily do is to have the function just execute Vasp, and the node('s executor) would control whether this is on the head process or it's getting shipped off. So it would look something like this:

```python
@node("energy_pot")
def get_energy(structure):
    vasp = pr.create.job.Vasp("vasp")
    # To be idempotent and functional, I guess we need either a `delete_existing_job=True`
    # Or a check to make sure `structure`and the structure of a loaded job (if loaded) 
    # are the same, just in case the node gets re-executed
    vasp.structure = structure
    vasp.run()  # Might need a try/except here, I forget what happens if you try to run a ran job
    return vasp.output.energy_pot[-1]
```

Then the executor would get the output processing function as a callback. There's some extra steps with serialization that can be done so you can recover completed tasks from file if the link between the node and executor gets irrevocably destroyed, but that's (a) doable and (b) for later.

Again, I'm not saying the idea of return values is rubbish, having the `Workflow` manage flow by return values is a reasonable paradigm and I think pretty closely aligned with `tiny_base`. But I don't like it as much, and it's not what's here already.

In microcosm, I also don't understand why we need a `suspended` return type in particular -- IMO the node is `running` whether it's hogging the head process or whether it shipped a task off to the queue and is waiting to start. From the workflow's perspective it's still sitting there trying hard to generate its output. If we switched over to a workflow-as-master paradigm maybe there is some use for it in terms of execution optimization or something, I just don't see it now.

**Comment by samwaseda** [comment] 2023-05-30 20:15
Ah ok I started seeing that you are saying the whole node is going to be submitted, correct? But in that case it might be necessary to pass the number of cores to the function, because in this very example the VASP job requires this information.

**Comment by liamhuber** [comment] 2023-05-30 21:35
>  you are saying the whole node is going to be submitted, correct?

Depending on your definition of "the whole node", yes. The idea is that the node will create a task and submit that to its executor; so not the entire node but its function and that function's arguments.

> But in that case it might be necessary to pass the number of cores to the function

Yes, possibly. The interaction with functions that evoke shell scripts is not entirely clear to me. It's also possible that we might delegate this work to a special `VaspExecutor`, and it is the executor that knows the number of cores to assign to each task and augments behaviour appropriately. Or perhaps in these cases the first argument of the node function is `self` and we have access to something like `self.executor.n_cores` in the node function. The cleanest solution with the current version of vasp jobs is definitely to pass the number of cores as an argument; in the future something more elegant may present itself.

**Comment by samwaseda** [comment] 2023-06-01 14:38
ok then let's forget about what I said about output (at least for now)

What do you think of extending `Signal` to include the current status, more or less as Jan defined it in the [job status class](https://github.com/pyiron/pyiron_base/blob/main/pyiron_base/jobs/job/extension/jobstatus.py)? Currently I'm already not very happy with the fact that there are loosely defined variables `running` and `failed`, and we can extend it to include `initialised` and `finished`? Importantly, there should be one status that can be chosen. That would allow `Workflow` to understand whether the current node can be executed.

**Comment by liamhuber** [comment] 2023-06-01 20:17
I would say table rather than forget, as it's a good idea 👍 b an alternative implementation.

Signal is intended to pulse and control callbacks, so I wouldn't be happy extending it in this way. You complaint about the status being dumb strings is super good though, and I agree mimicking the current status class is reasonable. IMO the way to do that is with a DataChannel. It would need to update at a bit of a different time than the regular output data channels, but I'm perfectly comfortable with that. The class is otherwise designed to handle exactly this sort of case.

Yes, Workflow would then be able to see what each node is up to, and I can see that this might become useful. I want to reiterate though that in the current implementation the Workflow instance is never responsible for executing nodes, execution happens directly as a result of node connections. One exception to this in the immediate future is when we define Workflow.run, which will serve as a jumping off point to get initial nodes running; I can the see how your idea is directly useful when we extend that so the workflow can restart from a spot that isn't the beginning. ATM we don't absolutely need a Channel to handle the status, a regular attribute would be ok too, but I do think slapping it on a Channel gives us nice options for using the information as part of the data flow later.

(Sorry for no code formatting, I'm on mobile and still haven't managed to figure out how to access the correct '...)

**Comment by samwaseda** [comment] 2023-06-01 20:38
> I want to reiterate though that in the current implementation the Workflow instance is never responsible for executing nodes, execution happens directly as a result of node connections.

Yeah that was only a language issue. What I meant was `Node` (or something that's attached to it).

> (Sorry for no code formatting, I'm on mobile and still haven't managed to figure out how to access the correct '...)

You have to press ' longer on your iPhone, then different types of quotation marks appear.

**Comment by liamhuber** [comment] 2023-06-01 20:43
`amazing, thank you`

**Comment by liamhuber** [comment] 2023-06-28 22:10
Keeping in mind there's an alternative paradigm stored here, I think that the outstanding issue of data initialization is superceded in #752 and we can close this now.

**Closed by liamhuber** 2023-06-28 22:10 UTC
